spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "goodbye"
trigger = { type = "timer" }
version = "0.1.0"

[[component]]
id = "goodbye"
source = "target/wasm32-wasi/release/goodbye.wasm"
[component.trigger]
queue_url = "ARSE"
[component.build]
command = "cargo build --target wasm32-wasi --release"
